import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/animacao-scroll.js';
import initAccordion from './modules/accordionFaq.js';
import initTabNav from './modules/tabNav.js';
import initModal from './modules/modal.js';
import tooltip from './modules/tooltip.js';
import dropdownMenu from './modules/dropdown.js';
import initMenuMobile from './modules/menu-mobile.js';
initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
tooltip();
dropdownMenu();
initMenuMobile();
